### ISSUE TITLE
Apple Mail/iOS Mail

### ISSUE THREAD

**Issue by SteffanCline** [Tiliq/autodiscover.xml#2]
Has anyone been able to successfully get Apple to query your server? I've tried everything to figure this out. I have the DNS set up as best I can tell but never see a DNS query against my servers or a request from apache for the config. Using tcpdump I can only see a bunch of DNS queries to Apple and then an https request that's encrypted so I can't tell what's happening.

**Comment by kevinmartin** [comment]
Unfortunately, Apple only really checks this endpoint if the email account is setup at an Exchange(-compatible) account.
