### ISSUE TITLE
Typo in index.js at line 55

### ISSUE THREAD

**Issue by zizzo81** [Tiliq/autodiscover.xml#3]
There's a typo here:

`	this.set('Content-Type', 'application/x-apple-aspen-config; chatset=utf-8');`

Should be

`	this.set('Content-Type', 'application/x-apple-aspen-config; charset=utf-8');`

**Comment by kevinmartin** [comment]
Thanks for the ticket. Fixed in https://github.com/Tiliq/autodiscover.xml/commit/cf234b0a2ec4be8204b168d553424a56c4d3c1c3

Released as [`v1.0.1`](https://github.com/Tiliq/autodiscover.xml/releases/tag/v1.0.1)
